
# SPDX-License-Identifier: Apache-2.0
version: '2.1'

volumes:
  pgdata:
  walletstore:

networks:
  mynetwork.com:
    external:
      name: fabricnet_test

services:

  explorerdb.mynetwork.com:
    image: hyperledger/explorer-db:latest
    container_name: explorerdb.com
    hostname: explorerdb.com
    environment:
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWORD=password
    healthcheck:
      test: "pg_isready -h localhost -p 5432 -q -U postgres"
      interval: 30s
      timeout: 10s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      -  mynetwork.com

  explorer.mynetwork.com:
    image:  hyperledger/explorer:latest
    container_name: explorer.com
    hostname: explorer.com
    environment:
      - DATABASE_HOST=explorerdb.com
      - DATABASE_DATABASE=fabricexplorer
      - DATABASE_USERNAME=hppoc
      - DATABASE_PASSWD=password
      - LOG_LEVEL_APP=debug
      - LOG_LEVEL_DB=debug
      - LOG_LEVEL_CONSOLE=info
      - LOG_CONSOLE_STDOUT=true
      - DISCOVERY_AS_LOCALHOST=false
    volumes:
      - ./dockerConfig/config.json:/opt/explorer/app/platform/fabric/config.json
      - ./dockerConfig/connection-profile:/opt/explorer/app/platform/fabric/connection-profile
      - ./dockerConfig/crypto-config:/tmp/crypto
      - walletstore:/opt/explorer/wallet
    ports:
      - 8080:8080
    depends_on:
      explorerdb.mynetwork.com:
        condition: service_healthy
    networks:
      -  mynetwork.com
